application: mealtrack
version: 1
runtime: python
api_version: 1


builtins:
- datastore_admin: on

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(.*)
  script: index.py
